function [ddpcx,ddpcy,ddsita] = autoGen_hoppingDynamics(pcx,pcy,sita,dpcx,dpcy,dsita,pex,pey,fx,fy,m,g,I)
%AUTOGEN_HOPPINGDYNAMICS
%    [DDPCX,DDPCY,DDSITA] = AUTOGEN_HOPPINGDYNAMICS(PCX,PCY,SITA,DPCX,DPCY,DSITA,PEX,PEY,FX,FY,M,G,I)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    19-Nov-2020 18:57:28

t2 = 1.0./m;
ddpcx = fx.*t2;
if nargout > 1
    ddpcy = t2.*(fy-g.*m);
end
if nargout > 2
    ddsita = (fx.*pcy-fy.*pcx-fx.*pey+fy.*pex+g.*m.*pcx.*2.0)./I;
end
