function [ddpcx,ddpcy,ddsita] = autoGen_hoppingDyn_lagrange(pcx,pcy,sita,dpcx,dpcy,dsita,pex,pey,fx,fy,m,g,I)
%AUTOGEN_HOPPINGDYN_LAGRANGE
%    [DDPCX,DDPCY,DDSITA] = AUTOGEN_HOPPINGDYN_LAGRANGE(PCX,PCY,SITA,DPCX,DPCY,DSITA,PEX,PEY,FX,FY,M,G,I)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    04-Feb-2021 19:36:12

t2 = 1.0./m;
ddpcx = fx.*t2;
if nargout > 1
    ddpcy = t2.*(fy-g.*m);
end
if nargout > 2
    ddsita = (fx.*pcy-fy.*pcx-fx.*pey+fy.*pex)./I;
end
